server:
  port: 8081

spring:
  application:
    name: api-tests


  graphql:
    path: /graphql           # endpoint для GraphQL
    graphiql:
      enabled: true          # если используешь GraphiQL Spring Boot Starter (не WebJar)
      path: /graphiql
    cors:
      allowed-origins: "*"   # разрешаем CORS со всех доменов
      allowed-methods: GET, POST
      allowed-headers: "*"

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/static/ # чтобы отдавать WebJar и HTML UI

  datasource:
    url: jdbc:postgresql://localhost:54321/habrdb1
    username: habrpguser1
    password: pgpwd4habr
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

testing:
  app:
    secret: Yp6qCka3mO6RYzyPggsu4GNFTOmc/SbHqY1ZJEDr5p0wSxywAPvB3GLTba8MbLAdFSDxT87ISv7VhY/Z/JTnSw==
    lifetime: 60000
    refreshSecret: Yp6qCka3mO6RYzyPggsu4GNFTOmc/SbHqY1ZJEDr5p0wSxywAPvB3GLTba8MbLAdFSDxT87ISv7VhY/Z/JTnSw==
    refreshLifetime: 600000

logging:
  level:
    root: INFO
    org.example.springpractice: DEBUG